// <auto-generated />
using System;
using DoAnOlympics.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAnOlympics.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260925124223_ThemLoaiHinhChuyenVaTripLog")]
    partial class ThemLoaiHinhChuyenVaTripLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAnOlympics.Api.Models.ContainerRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ChecksumHopLe")
                        .HasColumnType("bit");

                    b.Property<bool>("DaGhiSheet")
                        .HasColumnType("bit");

                    b.Property<string>("DiaDiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int?>("LoaiHinhChuyenId")
                        .HasColumnType("int");

                    b.Property<string>("MaContainer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhanCongChuyenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianQuet")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("LoaiHinhChuyenId");

                    b.HasIndex("PhanCongChuyenId");

                    b.ToTable("ContainerRecords");
                });

            modelBuilder.Entity("DoAnOlympics.Api.Models.DonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("NgayChay")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TuyenDuongId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaDon")
                        .IsUnique();

                    b.HasIndex("NgayChay");

                    b.HasIndex("TuyenDuongId");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("DoAnOlympics.Api.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaTaiXe")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MaTaiXe")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("DoAnOlympics.Api.Models.LoaiHinhChuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoaiHinhChuyens");
                });

            modelBuilder.Entity("DoAnOlympics.Api.Models.PhanCongChuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DonHangId")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DonHangId");

                    b.HasIndex("DriverId");

                    b.ToTable("PhanCongChuyens");
                });

            modelBuilder.Entity("DoAnOlympics.Api.Models.QuanLy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("QuanLys");
                });

            modelBuilder.Entity("DoAnOlympics.Api.Models.TinNhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("AnhDinhKem")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("AnhDinhKemLoaiNoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("LoaiSuCo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiGui")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DriverId", "ThoiGian");

                    b.ToTable("TinNhans");
                });

            modelBuilder.Entity("DoAnOlympics.Api.Models.TuyenDuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiemDen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiemDi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("KhoangCachKm")
                        .HasColumnType("float");

                    b.Property<string>("TenTuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TuyenDuongs");
                });

            modelBuilder.Entity("DoAnOlympics.Api.Models.ContainerRecord", b =>
                {
                    b.HasOne("DoAnOlympics.Api.Models.Driver", "Driver")
                        .WithMany("ContainerRecords")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnOlympics.Api.Models.LoaiHinhChuyen", "LoaiHinhChuyen")
                        .WithMany()
                        .HasForeignKey("LoaiHinhChuyenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DoAnOlympics.Api.Models.PhanCongChuyen", "PhanCongChuyen")
                        .WithMany("ContainerRecords")
                        .HasForeignKey("PhanCongChuyenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Driver");

                    b.Navigation("LoaiHinhChuyen");

                    b.Navigation("PhanCongChuyen");
                });

            modelBuilder.Entity("DoAnOlympics.Api.Models.DonHang", b =>
                {
                    b.HasOne("DoAnOlympics.Api.Models.TuyenDuong", "TuyenDuong")
                        .WithMany("DonHangs")
                        .HasForeignKey("TuyenDuongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TuyenDuong");
                });

            modelBuilder.Entity("DoAnOlympics.Api.Models.PhanCongChuyen", b =>
                {
                    b.HasOne("DoAnOlympics.Api.Models.DonHang", "DonHang")
                        .WithMany("PhanCongChuyens")
                        .HasForeignKey("DonHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnOlympics.Api.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("DoAnOlympics.Api.Models.TinNhan", b =>
                {
                    b.HasOne("DoAnOlympics.Api.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("DoAnOlympics.Api.Models.DonHang", b =>
                {
                    b.Navigation("PhanCongChuyens");
                });

            modelBuilder.Entity("DoAnOlympics.Api.Models.Driver", b =>
                {
                    b.Navigation("ContainerRecords");
                });

            modelBuilder.Entity("DoAnOlympics.Api.Models.PhanCongChuyen", b =>
                {
                    b.Navigation("ContainerRecords");
                });

            modelBuilder.Entity("DoAnOlympics.Api.Models.TuyenDuong", b =>
                {
                    b.Navigation("DonHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
